---



- name: "update apt"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade apt packages"
  become: true
  apt:
    upgrade: "yes"

- name: "Remove packages that are no longer used"
  become: true
  apt:
    autoremove: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["tar", "unzip", "curl", "git"]
    state: latest
    update_cache: yes


- name: "install node.js13"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x 
    sudo apt-get update
    sudo apt install -y nodejs
    

- name: "install pm2 Globally"
  npm:
     name: pm2
     global: yes