- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

# - name: Creates directory
#   file:
#     path: ~/backend-artifact
#     state: directory

# copy the files to ec2
- name: "copy file to ec2"
  copy:
    src: "artifact.tar.gz"
    dest: "~/"

- name: "Unarchive"
  unarchive:
    src: artifact.tar.gz
    dest: ~/


- name: "Executing Node app with PM2"
  shell: |
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start
  # register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu